### PR TITLE
Boolean Variants proposal

### PR DESCRIPTION
**Pull request by willcosgrove**
This is an API I've been playing around with in my own projects for defining boolean variants. This is just a proposal, and I'm definitely open to API suggestions, or just scrapping it altogether if it's not beneficial.

Boolean variants work by defining a variant and setting it's value to a String.

```ruby
classes = ClassVariants.build(
  variants: {
    block: "w-full justify-center"
  },
  defaults: {
    block: false
  }
)
classes.render # => ""
classes.render(block: true) # => "w-full justify-center"
```

A part of the API that I'm less sure is a good idea is the ability to define the inverse by prefixing the key with a `!`.

```ruby
classes = ClassVariants.build(
  variants: {
    block: "w-full justify-center",
    "!block": "w-auto"
  },
  defaults: {
    block: false
  }
)

classes.render # => "w-auto"
classes.render(block: true) # => "w-full justify-center"
```

I'm less confident because I don't love that you have to quote the key to make it a valid symbol, and it's also maybe just easier/clearer at that point to define the variant like so:

```ruby
classes = ClassVariants.build(
  variants: {
    block: {
      true => "w-full justify-center",
      false => "w-auto",
    },
  },
  defaults: {
    block: false
  }
)
```

The implementation I currently have has no effect on render speed, because it expands the boolean variants into normal hash/enum variants at initialization time. However it could negatively impact performance if the users application is creating lots of `ClassVariants` objects. In my use case, I'm using this inside a Phlex view, and it's stored in a constant, so these objects are getting built at start up and then left in memory for the life span of the application. In that use case, this would be a zero cost abstraction during view rendering.

I considered using a `!` suffix instead of a prefix, because that is a valid symbol without the need for quoting, which looks nicer in my opinion. But that pattern is being used in Phlex to define overrides, and this is not the same as that. I'd hate to overload patterns like that with different meanings. And `!` at the end is not connotative of `not` in ruby, so it doesn't work as well for expressing the meaning.

### CODE REVIEW

**Comment by adrianthedev** [comment]
This is good! I mean, I see why boolean would be useful, and maybe more useful the reverse variant.

As for the API, my gut would go with "do what's more conventional so more people understand it at first glance". So the `!block` would prevail there even if it's more cumbersome to write.

Another thing I thought about, but I'm not that fond of is to use a tuple and have the first value as the `true` and the second as `false`. WDYT?

```ruby
classes = ClassVariants.build(
  variants: {
    block: ["w-full justify-center", "w-auto"]
  },
  defaults: {
    block: false
  }
)
```


Now, for the second part, we could use an array on the builder instead of the hash for boolean values. But I'm wondering if we're going too off into the weeds. Be honest 😅

```ruby
classes = ClassVariants.build(
  variants: {
    block: ["w-full justify-center", "w-auto"]
  },
  defaults: {
    block: false
  }
)
classes.render # => ""

# this one here👇
classes.render(:block) # => "w-full justify-center"
```

**Comment by willcosgrove** [comment]
Regarding the `[true_case, false_case]` tuple idea, the main negative that comes up to me is that I would probably at a glance mistake that as just being a list of class names, instead of two sets of class names used in different cases. It seems like a lot of HTML class related ruby helpers will either work with strings or arrays to build the token list. So this would potentially clash with that intuition. But I do like the conciseness of it. I guess the worry I would have is just that it takes away the option to one day provide classes as an array of strings, instead of as a string.

The reason why I think providing classes as an array of strings might be useful is that it allows you to _remove_ a specific class a little easier. I haven't yet come up with a API that I like for doing that, but it's another thing I've been playing around with. Imagine you have a specific variant that needs to "overwrite" the class set in another variant. I currently do that by using a "!" prefixed class (which in Tailwind will make that style declared as `!important`) but it would be nice to have a way to say "here are the classes I want to add if this variant is chosen, and here are the classes I want to remove if this variant is chosen". But that is a proposal for another day 😄 

And regarding the array rendering, I think that's a viable option. I'm not sure how much I would personally find myself using it. I'm normally using these ClassVariants in Phlex or ViewComponent components, and so those boolean variants are going to be controllable from some state within the component normally, so I'm going to want to specify `render(block: block?)` or something to that effect.

But I could imagine someone wanting to write it like that. I'd be curious what performance hit would happen by accepting a splat arg in render. Anytime I'm working with stuff in the view layer that's going to be running potentially thousands of times in the course of one page render, I'm always worried about how it's going to impact performance 😄

**Comment by adrianthedev** [comment]
You are 100% right on the tuple/array issue. I don't know how it didn't cross my mind.
Yeah, using arrays to declare classes is something that we should support.

> "here are the classes I want to add if this variant is chosen, and here are the classes I want to remove if this variant is chosen". But that is a proposal for another day 😄

Yeah, I'm up for supporting that, on a need basis. So, let's wait until that scenario comes in?

> I'd be curious what performance hit would happen by accepting a splat arg in render

I gotta be honest and say that I never thought about performance that much. I appreciate that you do.

> And regarding the array rendering, I think that's a viable option. I'm not sure how much I would personally find myself using it.

Yeah, let's scratch that until we have a real need for that.


I'm curious about something. What are your opinions on the names of the methods? Do `build` and `render` convey the right message? Would you have picked other names?

**Comment by adrianthedev** [comment]
I haven't answered about the inverse variant. I'm good to merge the `!block` variant until we come up with a better solution.

**Comment by willcosgrove** [comment]
> I'm curious about something. What are your opinions on the names of the methods? Do build and render convey the right message? Would you have picked other names?

I like those names! I might have even gone more terse on the build method. Something like...

```ruby
module ClassVariants
  class << self
    def [](...) = Instance.new(...)
  end
end
```

So you could do

```ruby
class MyComponent < Phlex::HTML
  CLASSES = ClassVariants[
    "my default classes",
    variants: { ... },
    defaults: { ... }
  ]
end
```

But I think `build` is perfectly fine. I think it's good that it's not `new` because that makes it a little clearer that you are not actually creating an instance of `ClassVariants`.

And I like `render` as well. It might be nice if it was aliased to `call`. That would let you call it using the special `call` syntax if someone was so inclined.

```ruby
CLASSES.(size: :lg, color: :red, block: true)
```

**Comment by adrianthedev** [comment]
Got it! This seems a bit too smart for my taste. I love the "scannability" of code. One can scan it quickly and understand what it does.

```ruby
  ClassVariants[
    "my default classes",
    variants: { ... },
    defaults: { ... }
  ]
```

Cool! Let me know when it's safe to merge 🙌

**Comment by willcosgrove** [comment]
Should be good to go!

**Comment by adrianthedev** [comment]
Thanks for your contributions @willcosgrove! Looking for to riffing together on new things.

**Pull request merged**
